### ISSUE TITLE
Some Part subtypes aren't showing upy

### ISSUE THREAD

**Issue by Darknesshas1** [blowfishpro/B9-Aerospace#35] opened 2016-10-17 10:37 UTC
I have several of the universal parts in the Structure tab that don't show up with any sub types when you click them

**Comment by blowfishpro** [comment] 2016-10-17 16:06
As usual with support requests, please provide logs.  No way to tell what the issue is without them.

**Comment by blowfishpro** [comment] 2016-10-24 06:54
Closing for now, re-open if you get the necessary info.

**Closed by blowfishpro** 2016-10-24 06:54 UTC
Labels: support
